[options]
colorscheme = "iceberg"
colorscheme_bg = "dark"
enable_guicolors = true
statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
enable_statusmode_tag = true
max_column = 80
bootstrap_after = "autoload#after"

[[layers]]
name = 'autocomplete'
auto-completion-delay = 500
auto-completion-return-key-behavior = "nil"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'fzf'

[[custom_plugins]]
name = 'cocopon/iceberg.vim'
